"""empty message

Revision ID: f3dc27809941
Revises: 0e1df43f2f8a
Create Date: 2021-12-12 23:55:10.784987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3dc27809941'
down_revision = '0e1df43f2f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reverb', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('dist', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('vibe', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('octave', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'octave')
    op.drop_column('user', 'vibe')
    op.drop_column('user', 'dist')
    op.drop_column('user', 'reverb')
    # ### end Alembic commands ###
